export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_FAILURE";

export const ADD_TO_WATCHLIST_REQUEST = "ADD_TO_WATCHLIST_REQUEST";
export const ADD_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_TO_WATCHLIST_FAILURE = "ADD_TO_WATCHLIST_FAILURE";

export const REMOVE_FROM_WATCHLIST_REQUEST = "REMOVE_FROM_WATCHLIST_REQUEST";
export const REMOVE_FROM_WATCHLIST_SUCCESS = "REMOVE_FROM_WATCHLIST_SUCCESS";
export const REMOVE_FROM_WATCHLIST_FAILURE = "REMOVE_FROM_WATCHLIST_FAILURE";
